export const TILE_MANIFEST = {
  "letters": [
    require('@/assets/images/tiles/letters/letter_a.png'),
    require('@/assets/images/tiles/letters/letter_b.png'),
    require('@/assets/images/tiles/letters/letter_c.png'),
    require('@/assets/images/tiles/letters/letter_d.png'),
    require('@/assets/images/tiles/letters/letter_e.png'),
    require('@/assets/images/tiles/letters/letter_f.png'),
    require('@/assets/images/tiles/letters/letter_h.png'),
    require('@/assets/images/tiles/letters/letter_k.png'),
    require('@/assets/images/tiles/letters/letter_l.png'),
    require('@/assets/images/tiles/letters/letter_m.png'),
    require('@/assets/images/tiles/letters/letter_n.png'),
    require('@/assets/images/tiles/letters/letter_o.png'),
    require('@/assets/images/tiles/letters/letter_p.png'),
    require('@/assets/images/tiles/letters/letter_r.png'),
    require('@/assets/images/tiles/letters/letter_s.png'),
    require('@/assets/images/tiles/letters/letter_t.png'),
    require('@/assets/images/tiles/letters/letter_u.png'),
    require('@/assets/images/tiles/letters/letter_v.png'),
    require('@/assets/images/tiles/letters/letter_w.png'),
    require('@/assets/images/tiles/letters/letter_x.png'),
    require('@/assets/images/tiles/letters/letter_y.png'),
    require('@/assets/images/tiles/letters/letter_z.png')
  ],
  "lines": [
    require('@/assets/images/tiles/lines/line_00.png'),
    require('@/assets/images/tiles/lines/line_01.png'),
    require('@/assets/images/tiles/lines/line_02.png'),
    require('@/assets/images/tiles/lines/line_03.png'),
    require('@/assets/images/tiles/lines/line_04.png'),
    require('@/assets/images/tiles/lines/line_05.png'),
    require('@/assets/images/tiles/lines/line_06.png'),
    require('@/assets/images/tiles/lines/line_07.png'),
    require('@/assets/images/tiles/lines/line_08.png'),
    require('@/assets/images/tiles/lines/line_09.png'),
    require('@/assets/images/tiles/lines/line_10.png'),
    require('@/assets/images/tiles/lines/line_11.png'),
    require('@/assets/images/tiles/lines/line_12.png'),
    require('@/assets/images/tiles/lines/line_13.png'),
    require('@/assets/images/tiles/lines/line_14.png'),
    require('@/assets/images/tiles/lines/line_15.png')
  ],
  "shapes": [
    require('@/assets/images/tiles/shapes/circle_00.png'),
    require('@/assets/images/tiles/shapes/circle_01.png'),
    require('@/assets/images/tiles/shapes/circle_02.png'),
    require('@/assets/images/tiles/shapes/circle_03.png'),
    require('@/assets/images/tiles/shapes/circle_04.png'),
    require('@/assets/images/tiles/shapes/circle_05.png'),
    require('@/assets/images/tiles/shapes/circle_06.png'),
    require('@/assets/images/tiles/shapes/circle_07.png'),
    require('@/assets/images/tiles/shapes/square_00.png'),
    require('@/assets/images/tiles/shapes/square_01.png'),
    require('@/assets/images/tiles/shapes/square_02.png'),
    require('@/assets/images/tiles/shapes/square_03.png'),
    require('@/assets/images/tiles/shapes/square_04.png'),
    require('@/assets/images/tiles/shapes/square_05.png'),
    require('@/assets/images/tiles/shapes/square_06.png'),
    require('@/assets/images/tiles/shapes/square_07.png'),
    require('@/assets/images/tiles/shapes/square_08.png'),
    require('@/assets/images/tiles/shapes/square_09.png'),
    require('@/assets/images/tiles/shapes/square_10.png'),
    require('@/assets/images/tiles/shapes/square_11.png'),
    require('@/assets/images/tiles/shapes/triangle_00.png'),
    require('@/assets/images/tiles/shapes/triangle_01.png'),
    require('@/assets/images/tiles/shapes/triangle_02.png'),
    require('@/assets/images/tiles/shapes/triangle_03.png'),
    require('@/assets/images/tiles/shapes/triangle_04.png'),
    require('@/assets/images/tiles/shapes/triangle_05.png'),
    require('@/assets/images/tiles/shapes/triangle_06.png'),
    require('@/assets/images/tiles/shapes/triangle_07.png'),
    require('@/assets/images/tiles/shapes/triangle_08.png')
  ],
  "tilerTest": [
    require('@/assets/images/tiles/tilerTest/tile_00000000.png'),
    require('@/assets/images/tiles/tilerTest/tile_00000101.png'),
    require('@/assets/images/tiles/tilerTest/tile_00001000.png'),
    require('@/assets/images/tiles/tilerTest/tile_00010001.png'),
    require('@/assets/images/tiles/tilerTest/tile_01000010.png'),
    require('@/assets/images/tiles/tilerTest/tile_01010010.png'),
    require('@/assets/images/tiles/tilerTest/tile_01010101.png'),
    require('@/assets/images/tiles/tilerTest/tile_10000010.png'),
    require('@/assets/images/tiles/tilerTest/tile_10001000.png'),
    require('@/assets/images/tiles/tilerTest/tile_10001010.png'),
    require('@/assets/images/tiles/tilerTest/tile_10101010.png')
  ]
} as const;

export type TileCategory = keyof typeof TILE_MANIFEST;
export const TILE_CATEGORIES = Object.keys(TILE_MANIFEST) as TileCategory[];
